# Makefile.in generated by automake 1.9.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

include ./Rules.make

COMMON = $(PROJECT_DIR)/src/common
STREAM = $(PROJECT_DIR)/src/stream
SRC = $(PROJECT_DIR)/src

all:
	cd $(COMMON) ; $(MAKE)
	cd $(STREAM) ; $(MAKE)
	cd $(SRC) ; $(MAKE)

install:
	cd $(COMMON) ; $(MAKE) install
	cd $(STREAM) ; $(MAKE) install
	cd $(SRC) ; $(MAKE) install

clean:
	cd $(COMMON) ; $(MAKE) clean
	cd $(STREAM) ; $(MAKE) clean
	cd $(SRC) ; $(MAKE) clean


	rm -f $(PROJECT_DIR)/bin/*
